version: '3'
services:
  newzen_api:
    container_name: "sms-mini-app"
    image: "sms-mini-app"
    build:
      dockerfile: Dockerfile
      args:
        docker_env: dev
    ports:
      - 7632:80
    privileged: true
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./web:/app/web
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
