<?php

namespace app\modules;

use app\modules\v1\VersionModule;
use yii\base\Module as BaseModule;
use yii\filters\Cors;
use yii\filters\VerbFilter;

class Module extends BaseModule
{
    public function init()
    {
        $this->modules = [
            "v1" => VersionModule::class
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            'class' => Cors::class, // the new Cors class inherited from yii2's
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'OPTIONS', 'DELETE', 'PATCH', 'PUT'],
                'Access-Control-Request-Headers' => ['Origin', 'X-Requested-With', 'Content-Type', 'accept', 'Authorization', 'G-ClientID', 'UserIP']
            ],
        ];
        /* Default Validate Method */
        return $behaviors;
    }
}