<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\AppQuery;

/**
 * This is the base-model class for table "apps".
 *
 * @property integer $id
 * @property string $version
 * @property integer $version_level
 * @property integer $required_update
 * @property string $description_upgrade
 * @property string $link
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class App extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'apps';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['version_level', 'required_update', 'status'], 'integer'],
            [['description_upgrade'], 'string'],
            [['version', 'link'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'version' => 'Version',
            'version_level' => 'Version Level',
            'required_update' => 'Required Update',
            'description_upgrade' => 'Description Upgrade',
            'link' => 'Link',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return AppQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AppQuery(static::class);
    }
}
