<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\DeviceTokenQuery;

/**
 * This is the base-model class for table "device_tokens".
 *
 * @property integer $id
 * @property integer $device_id
 * @property string $type
 * @property string $token
 * @property integer $expire_at
 * @property string $deleted_at
 * @property string $created_at
 * @property string $updated_at
 */
abstract class DeviceToken extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'device_tokens';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['device_id', 'type', 'token'], 'required'],
            [['device_id', 'expire_at'], 'integer'],
            [['deleted_at'], 'safe'],
            [['type'], 'string', 'max' => 255],
            [['token'], 'string', 'max' => 40]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'device_id' => 'Device ID',
            'type' => 'Type',
            'token' => 'Token',
            'expire_at' => 'Expire At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ]);
    }

    /**
     * @inheritdoc
     * @return DeviceTokenQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DeviceTokenQuery(static::class);
    }
}
