<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\OrderQuery;

/**
 * This is the base-model class for table "orders".
 *
 * @property integer $id
 * @property integer $device_id
 * @property integer $package_id
 * @property integer $status
 * @property string $expired_at
 * @property string $type
 * @property string $provider_code
 * @property string $customer
 * @property double $price
 * @property string $provider_note
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Order extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['device_id', 'package_id', 'status'], 'integer'],
            [['expired_at'], 'safe'],
            [['price'], 'number'],
            [['provider_note'], 'string'],
            [['type'], 'string', 'max' => 100],
            [['provider_code'], 'string', 'max' => 50],
            [['customer'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'device_id' => 'Device ID',
            'package_id' => 'Package ID',
            'status' => 'Status',
            'expired_at' => 'Expired At',
            'type' => 'Type',
            'provider_code' => 'Provider Code',
            'created_at' => 'Created At',
            'customer' => 'Customer',
            'price' => 'Price',
            'provider_note' => 'Provider Note',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return OrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new OrderQuery(static::class);
    }
}
