<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\PackageQuery;

/**
 * This is the base-model class for table "packages".
 *
 * @property integer $id
 * @property string $code
 * @property double $price
 * @property string $deleted_at
 * @property string $use_duration
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Package extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'packages';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['price'], 'number'],
            [['deleted_at'], 'safe'],
            [['code', 'use_duration'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'code' => 'Code',
            'created_at' => 'Created At',
            'price' => 'Price',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'use_duration' => 'Use Duration',
        ]);
    }

    /**
     * @inheritdoc
     * @return PackageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PackageQuery(static::class);
    }
}
