<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use \app\models\SessionWorkQuery;

/**
 * This is the base-model class for table "session_works".
 *
 * @property integer $id
 * @property array $report
 * @property string $filename
 * @property string $data
 * @property string $select_data
 * @property integer $is_session_current
 * @property integer $type
 * @property integer $created_by
 * @property string $created_at
 * @property string $updated_at
 */
abstract class SessionWork extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'session_works';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
            'updatedByAttribute' => false,
    ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['report'], 'safe'],
            [['data', 'select_data'], 'safe'],
            [['is_session_current', 'type'], 'integer'],
            [['filename'], 'string', 'max' => 500]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'created_by' => 'Created By',
            'report' => 'Report',
            'filename' => 'Filename',
            'data' => 'Data',
            'select_data' => 'Select Data',
            'is_session_current' => 'Is Session Current',
            'type' => 'Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return SessionWorkQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SessionWorkQuery(static::class);
    }
}
