<?php

namespace app\modules\v1\models\form;

use yii\base\Model;

class CheckoutFormGmail extends Model
{
    public $tenant_id;
    public $price;
    public $package_code;
    public $provider_code;

    public $title;

    public function formName()
    {
        return "";
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            [["tenant_id", "price", "provider_code", "package_code"], "required"],
            [["title", "provider_code"], "safe"],
            ['price', 'filter', 'filter' => 'floatval']
        ]); // TODO: Change the autogenerated stub
    }
}