<?php

namespace app\modules\v1\models\form;

use app\modules\v1\models\Device;

class DeviceForm extends Device
{
    public function rules()
    {
        return array_merge(parent::rules(), [
            ["device_uuid_hash", "required"]
        ]);
    }

    /**
     * @param $insert
     * @return bool
     */
    public function beforeSave($insert): bool
    {
        if ($insert) {
            $this->generateTenantId();
        }
        $this->logged_at = date("Y-m-d H:i:s");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function generateTenantId(): void
    {
        $this->tenant_id = time();
    }
}