<?php

namespace app\modules\v1\models\form;

use app\modules\v1\models\Device;
use Yii;

class DeviceForm extends Device
{
    public function rules()
    {
        return array_merge(parent::rules(), [
            ["device_uuid_hash", "required"]
        ]);
    }

    /**
     * @param $insert
     * @return bool
     */
    public function beforeSave($insert): bool
    {
        $this->logged_at = date("Y-m-d H:i:s");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            $this->generateTenantId();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function generateTenantId(): void
    {
        $idLast = Yii::$app->db->getLastInsertID();
        $this->tenant_id = 'D' . str_pad($idLast, 10, "0", STR_PAD_LEFT);
        $this->updateAttributes(["tenant_id" => $this->tenant_id]);
    }
}