<?php

namespace app\modules\v1\models\form;

use app\modules\v1\models\Device;

class UpdateTenantForm extends Device
{
    public function rules()
    {
        return array_merge(parent::rules(), [
            [["tenant_id"], "required"],
            [["tenant_id"], "unique"]
        ]); // TODO: Change the autogenerated stub
    }
}