<?php

namespace app\controllers;

use app\components\http\ResponseBuilder;
use yii\filters\ContentNegotiator;
use yii\filters\VerbFilter;
use yii\rest\Controller as BaseController;
use yii\web\Response;

/**
 * @property ResponseBuilder $responseBuilder
 */
class Controller extends BaseController
{
    public function behaviors()
    {
        return [
            'contentNegotiator' => [
                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                    'application/xml' => Response::FORMAT_XML,
                ],
            ],
            'verbFilter' => [
                'class' => VerbFilter::className(),
                'actions' => $this->verbs(),
            ]
        ];
    }

    public $responseBuilder;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->responseBuilder = new ResponseBuilder();
    }
}