<?php

namespace app\modules\v1;

use app\modules\Module;
use app\modules\v1\cms\CmsModule;
use app\modules\v1\public\PublicModule;
use app\modules\v1\web_portal\WebPortalModule;

class VersionModule extends Module
{
    public function init()
    {
        $this->modules = [
            "web_portal" => WebPortalModule::class,
            "public" => PublicModule::class,
            "cms" => CmsModule::class
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}