<?php

namespace app\models;

use app\behaviors\JsonBehavior;
use \app\models\base\SessionWork as BaseSessionWork;

/**
 * This is the model class for table "session_works".
 */
class SessionWork extends BaseSessionWork
{
    const TYPE_SMS = 1;
    const TYPE_CALL = 2;

    const IS_SESSION_CURRENT = 1;
    const NOT_IS_SESSION_CURRENT = 0;

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            [
                "class" => JsonBehavior::class,
                "jsonAttributes" => ["report"]
            ]
        ]); // TODO: Change the autogenerated stub
    }

    public function formName()
    {
        return "";
    }

    public function resetRollbackCurrent()
    {
        SessionWork::updateAll(["is_session_current" => self::NOT_IS_SESSION_CURRENT], ["created_by" => $this->created_by, "is_session_current" => self::IS_SESSION_CURRENT]);
    }
}
