<?php

namespace app\modules\v1\models;

use app\helpers\StringHelper;
use app\models\SessionWork as BaseSessionWork;

class SessionWork extends BaseSessionWork
{
    public $noDecodingSelectData = false;

    public function fields()
    {
        return array_merge(parent::fields(), [
            "data" => function () {
                return json_decode(StringHelper::unCompressString($this->data), true);
            },
            "select_data" => function () {
                if ($this->noDecodingSelectData) {
                    return StringHelper::unCompressString($this->select_data);
                }
                return json_decode(StringHelper::unCompressString($this->select_data), true);
            }
        ]); // TODO: Change the autogenerated stub
    }
}